query ListAllBusinesses @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  businesses {
    id
    name
    industry
    createdAt
  }
}

query GetBusinessDetails($id: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  business(id: $id) {
    id
    name
    description
    overallEsgScore
  }
}

mutation CreateBusiness($name: String!, $industry: String!, $overallEsgScore: Float!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  business_insert(data: {
    name: $name,
    industry: $industry,
    overallEsgScore: $overallEsgScore,
    createdAt_expr: "request.time"
  })
}