extend type Business {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Business", purpose: IMPLICIT_KEY_FIELD)
}
extend type EsgDetail {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "EsgDetail", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `EsgDetail`.`business`. It must match the value of `Business`.`id`. See `@ref` for how to customize it.
  """
  businessId: UUID @fdc_generated(from: "EsgDetail.business", purpose: IMPLICIT_REF_FIELD)
}
extend type ListBusiness {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ListBusiness", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ListBusiness`.`business`. It must match the value of `Business`.`id`. See `@ref` for how to customize it.
  """
  businessId: UUID @fdc_generated(from: "ListBusiness.business", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ListBusiness`.`userList`. It must match the value of `UserList`.`id`. See `@ref` for how to customize it.
  """
  userListId: UUID @fdc_generated(from: "ListBusiness.userList", purpose: IMPLICIT_REF_FIELD)
}
extend type Suggestion {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Suggestion", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Suggestion`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "Suggestion.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type UserList {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "UserList", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `UserList`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "UserList.user", purpose: IMPLICIT_REF_FIELD)
}
