extend type Document {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Document", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`initiative`. It must match the value of `Initiative`.`id`. See `@ref` for how to customize it.
  """
  initiativeId: UUID! @fdc_generated(from: "Document.initiative", purpose: IMPLICIT_REF_FIELD)
}
extend type ESGCategory {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ESGCategory", purpose: IMPLICIT_KEY_FIELD)
}
extend type Initiative {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Initiative", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Initiative`.`esgCategory`. It must match the value of `ESGCategory`.`id`. See `@ref` for how to customize it.
  """
  esgCategoryId: UUID! @fdc_generated(from: "Initiative.esgCategory", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Initiative`.`organization`. It must match the value of `Organization`.`id`. See `@ref` for how to customize it.
  """
  organizationId: UUID! @fdc_generated(from: "Initiative.organization", purpose: IMPLICIT_REF_FIELD)
}
extend type KPI {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "KPI", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `KPI`.`initiative`. It must match the value of `Initiative`.`id`. See `@ref` for how to customize it.
  """
  initiativeId: UUID! @fdc_generated(from: "KPI.initiative", purpose: IMPLICIT_REF_FIELD)
}
extend type Organization {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Organization", purpose: IMPLICIT_KEY_FIELD)
}
extend type ProgressUpdate {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ProgressUpdate", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ProgressUpdate`.`initiative`. It must match the value of `Initiative`.`id`. See `@ref` for how to customize it.
  """
  initiativeId: UUID! @fdc_generated(from: "ProgressUpdate.initiative", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ProgressUpdate`.`kpi`. It must match the value of `KPI`.`id`. See `@ref` for how to customize it.
  """
  kpiId: UUID! @fdc_generated(from: "ProgressUpdate.kpi", purpose: IMPLICIT_REF_FIELD)
}
