extend type Mutation {
  """
  ✨ Insert a single `Business` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  business_insert(
    """
    Data object to insert into the table.
    """
    data: Business_Data!
  ): Business_KeyOutput! @fdc_generated(from: "Business", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `EsgDetail` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  esgDetail_insert(
    """
    Data object to insert into the table.
    """
    data: EsgDetail_Data!
  ): EsgDetail_KeyOutput! @fdc_generated(from: "EsgDetail", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ListBusiness` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  listBusiness_insert(
    """
    Data object to insert into the table.
    """
    data: ListBusiness_Data!
  ): ListBusiness_KeyOutput! @fdc_generated(from: "ListBusiness", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Suggestion` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  suggestion_insert(
    """
    Data object to insert into the table.
    """
    data: Suggestion_Data!
  ): Suggestion_KeyOutput! @fdc_generated(from: "Suggestion", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserList` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userList_insert(
    """
    Data object to insert into the table.
    """
    data: UserList_Data!
  ): UserList_KeyOutput! @fdc_generated(from: "UserList", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Business` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  business_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Business_Data!]!
  ): [Business_KeyOutput!]! @fdc_generated(from: "Business", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `EsgDetail` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  esgDetail_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [EsgDetail_Data!]!
  ): [EsgDetail_KeyOutput!]! @fdc_generated(from: "EsgDetail", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ListBusiness` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  listBusiness_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ListBusiness_Data!]!
  ): [ListBusiness_KeyOutput!]! @fdc_generated(from: "ListBusiness", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Suggestion` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  suggestion_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Suggestion_Data!]!
  ): [Suggestion_KeyOutput!]! @fdc_generated(from: "Suggestion", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserList` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userList_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserList_Data!]!
  ): [UserList_KeyOutput!]! @fdc_generated(from: "UserList", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Business` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Business`.
  """
  business_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Business_Data!
  ): Business_KeyOutput! @fdc_generated(from: "Business", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `EsgDetail` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EsgDetail`.
  """
  esgDetail_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: EsgDetail_Data!
  ): EsgDetail_KeyOutput! @fdc_generated(from: "EsgDetail", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ListBusiness` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ListBusiness`.
  """
  listBusiness_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ListBusiness_Data!
  ): ListBusiness_KeyOutput! @fdc_generated(from: "ListBusiness", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Suggestion` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Suggestion`.
  """
  suggestion_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Suggestion_Data!
  ): Suggestion_KeyOutput! @fdc_generated(from: "Suggestion", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserList` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserList`.
  """
  userList_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserList_Data!
  ): UserList_KeyOutput! @fdc_generated(from: "UserList", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Business` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Business`.
  """
  business_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Business_Data!]!
  ): [Business_KeyOutput!]! @fdc_generated(from: "Business", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `EsgDetail` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EsgDetail`.
  """
  esgDetail_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [EsgDetail_Data!]!
  ): [EsgDetail_KeyOutput!]! @fdc_generated(from: "EsgDetail", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ListBusiness` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ListBusiness`.
  """
  listBusiness_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ListBusiness_Data!]!
  ): [ListBusiness_KeyOutput!]! @fdc_generated(from: "ListBusiness", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Suggestion` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Suggestion`.
  """
  suggestion_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Suggestion_Data!]!
  ): [Suggestion_KeyOutput!]! @fdc_generated(from: "Suggestion", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserList` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserList`.
  """
  userList_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserList_Data!]!
  ): [UserList_KeyOutput!]! @fdc_generated(from: "UserList", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Business` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Business` or `null` if not found.
  """
  business_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Business_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Business_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Business_Data!
  ): Business_KeyOutput @fdc_generated(from: "Business", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `EsgDetail` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `EsgDetail` or `null` if not found.
  """
  esgDetail_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: EsgDetail_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EsgDetail_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: EsgDetail_Data!
  ): EsgDetail_KeyOutput @fdc_generated(from: "EsgDetail", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ListBusiness` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ListBusiness` or `null` if not found.
  """
  listBusiness_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ListBusiness_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ListBusiness_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ListBusiness_Data!
  ): ListBusiness_KeyOutput @fdc_generated(from: "ListBusiness", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Suggestion` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Suggestion` or `null` if not found.
  """
  suggestion_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Suggestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Suggestion_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Suggestion_Data!
  ): Suggestion_KeyOutput @fdc_generated(from: "Suggestion", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserList` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserList` or `null` if not found.
  """
  userList_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserList_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserList_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserList_Data!
  ): UserList_KeyOutput @fdc_generated(from: "UserList", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Business` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  business_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Business_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Business_Data!
  ): Int! @fdc_generated(from: "Business", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `EsgDetail` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  esgDetail_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: EsgDetail_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: EsgDetail_Data!
  ): Int! @fdc_generated(from: "EsgDetail", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ListBusiness` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  listBusiness_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ListBusiness_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ListBusiness_Data!
  ): Int! @fdc_generated(from: "ListBusiness", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Suggestion` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  suggestion_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Suggestion_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Suggestion_Data!
  ): Int! @fdc_generated(from: "Suggestion", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserList` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userList_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserList_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserList_Data!
  ): Int! @fdc_generated(from: "UserList", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Business` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  business_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Business_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Business_FirstRow
  ): Business_KeyOutput @fdc_generated(from: "Business", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `EsgDetail` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  esgDetail_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: EsgDetail_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EsgDetail_FirstRow
  ): EsgDetail_KeyOutput @fdc_generated(from: "EsgDetail", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ListBusiness` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  listBusiness_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ListBusiness_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ListBusiness_FirstRow
  ): ListBusiness_KeyOutput @fdc_generated(from: "ListBusiness", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Suggestion` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  suggestion_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Suggestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Suggestion_FirstRow
  ): Suggestion_KeyOutput @fdc_generated(from: "Suggestion", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserList` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userList_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserList_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserList_FirstRow
  ): UserList_KeyOutput @fdc_generated(from: "UserList", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Business` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  business_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Business_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Business", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `EsgDetail` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  esgDetail_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: EsgDetail_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ListBusiness` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  listBusiness_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ListBusiness_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ListBusiness", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Suggestion` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  suggestion_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Suggestion_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserList` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userList_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserList_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserList", purpose: DELETE_MULTIPLE)
}
