extend type Query {
  """
  ✨ Look up a single `Business` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  business(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Business_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Business_FirstRow
  ): Business @fdc_generated(from: "Business", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `EsgDetail` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  esgDetail(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: EsgDetail_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EsgDetail_FirstRow
  ): EsgDetail @fdc_generated(from: "EsgDetail", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ListBusiness` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  listBusiness(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ListBusiness_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ListBusiness_FirstRow
  ): ListBusiness @fdc_generated(from: "ListBusiness", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Suggestion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  suggestion(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Suggestion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Suggestion_FirstRow
  ): Suggestion @fdc_generated(from: "Suggestion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserList` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userList(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserList_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserList_FirstRow
  ): UserList @fdc_generated(from: "UserList", purpose: QUERY_SINGLE)
  """
  ✨ List `Business` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  businesses(
    """
    Filter condition to narrow down the query results.
    """
    where: Business_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Business_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Business_Having
  ): [Business!]! @fdc_generated(from: "Business", purpose: QUERY_MULTIPLE)
  """
  ✨ List `EsgDetail` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  esgDetails(
    """
    Filter condition to narrow down the query results.
    """
    where: EsgDetail_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EsgDetail_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EsgDetail_Having
  ): [EsgDetail!]! @fdc_generated(from: "EsgDetail", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ListBusiness` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  listBusinesses(
    """
    Filter condition to narrow down the query results.
    """
    where: ListBusiness_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ListBusiness_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ListBusiness_Having
  ): [ListBusiness!]! @fdc_generated(from: "ListBusiness", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Suggestion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  suggestions(
    """
    Filter condition to narrow down the query results.
    """
    where: Suggestion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Suggestion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Suggestion_Having
  ): [Suggestion!]! @fdc_generated(from: "Suggestion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserList` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userLists(
    """
    Filter condition to narrow down the query results.
    """
    where: UserList_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserList_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserList_Having
  ): [UserList!]! @fdc_generated(from: "UserList", purpose: QUERY_MULTIPLE)
}
