extend type Business {
  """
  ✨ List `EsgDetail` objects in a one-to-many relationship (where `EsgDetail`.`business` is this object).
  """
  esgDetails_on_business(
    """
    Filter condition to narrow down the query results.
    """
    where: EsgDetail_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EsgDetail_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EsgDetail_Having
  ): [EsgDetail!]! @fdc_generated(from: "EsgDetail.business", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `ListBusiness` objects in a one-to-many relationship (where `ListBusiness`.`business` is this object).
  """
  listBusinesses_on_business(
    """
    Filter condition to narrow down the query results.
    """
    where: ListBusiness_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ListBusiness_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ListBusiness_Having
  ): [ListBusiness!]! @fdc_generated(from: "ListBusiness.business", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Business", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Business` table.
  """
  _count: Int! @fdc_generated(from: "Business.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `environmentalScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  environmentalScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.environmentalScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `governanceScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  governanceScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.governanceScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `industry` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  industry_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.industry", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `overallEsgScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  overallEsgScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.overallEsgScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `socialScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  socialScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.socialScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `website` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  website_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.website", purpose: QUERY_COUNT)
  """
  ✨ Sum the `environmentalScore` field in the `Business` table.
  """
  environmentalScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.environmentalScore", purpose: QUERY_SUM)
  """
  ✨ Sum the `governanceScore` field in the `Business` table.
  """
  governanceScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.governanceScore", purpose: QUERY_SUM)
  """
  ✨ Sum the `overallEsgScore` field in the `Business` table.
  """
  overallEsgScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.overallEsgScore", purpose: QUERY_SUM)
  """
  ✨ Sum the `socialScore` field in the `Business` table.
  """
  socialScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.socialScore", purpose: QUERY_SUM)
  """
  ✨ Average the `environmentalScore` field in the `Business` table.
  """
  environmentalScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.environmentalScore", purpose: QUERY_AVG)
  """
  ✨ Average the `governanceScore` field in the `Business` table.
  """
  governanceScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.governanceScore", purpose: QUERY_AVG)
  """
  ✨ Average the `overallEsgScore` field in the `Business` table.
  """
  overallEsgScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.overallEsgScore", purpose: QUERY_AVG)
  """
  ✨ Average the `socialScore` field in the `Business` table.
  """
  socialScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Business.socialScore", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Business` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Business.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `environmentalScore` field in the `Business` table.
  """
  environmentalScore_min: Float @fdc_generated(from: "Business.environmentalScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `governanceScore` field in the `Business` table.
  """
  governanceScore_min: Float @fdc_generated(from: "Business.governanceScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `overallEsgScore` field in the `Business` table.
  """
  overallEsgScore_min: Float @fdc_generated(from: "Business.overallEsgScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `socialScore` field in the `Business` table.
  """
  socialScore_min: Float @fdc_generated(from: "Business.socialScore", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Business` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Business.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `environmentalScore` field in the `Business` table.
  """
  environmentalScore_max: Float @fdc_generated(from: "Business.environmentalScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `governanceScore` field in the `Business` table.
  """
  governanceScore_max: Float @fdc_generated(from: "Business.governanceScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `overallEsgScore` field in the `Business` table.
  """
  overallEsgScore_max: Float @fdc_generated(from: "Business.overallEsgScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `socialScore` field in the `Business` table.
  """
  socialScore_max: Float @fdc_generated(from: "Business.socialScore", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Business.id", purpose: ENTITY_ID)
}
extend type EsgDetail {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "EsgDetail", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `EsgDetail` table.
  """
  _count: Int! @fdc_generated(from: "EsgDetail.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `EsgDetail` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `EsgDetail` table where the `category` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  category_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail.category", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `EsgDetail` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `EsgDetail` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `EsgDetail` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `EsgDetail` table where the `sourceUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sourceUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "EsgDetail.sourceUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `EsgDetail` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "EsgDetail.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `EsgDetail` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "EsgDetail.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "EsgDetail.id", purpose: ENTITY_ID)
}
extend type ListBusiness {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ListBusiness", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ListBusiness` table.
  """
  _count: Int! @fdc_generated(from: "ListBusiness.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ListBusiness` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ListBusiness.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ListBusiness` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ListBusiness.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ListBusiness` table where the `note` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  note_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ListBusiness.note", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ListBusiness` table where the `position` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  position_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ListBusiness.position", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ListBusiness` table where the `userListId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userListId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ListBusiness.userListId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `position` field in the `ListBusiness` table.
  """
  position_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "ListBusiness.position", purpose: QUERY_SUM)
  """
  ✨ Average the `position` field in the `ListBusiness` table.
  """
  position_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "ListBusiness.position", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `position` field in the `ListBusiness` table.
  """
  position_min: Int @fdc_generated(from: "ListBusiness.position", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `position` field in the `ListBusiness` table.
  """
  position_max: Int @fdc_generated(from: "ListBusiness.position", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ListBusiness.id", purpose: ENTITY_ID)
}
extend type Suggestion {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Suggestion", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Suggestion` table.
  """
  _count: Int! @fdc_generated(from: "Suggestion.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `businessName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.businessName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `details` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  details_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.details", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `targetBusinessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  targetBusinessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.targetBusinessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.type", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Suggestion` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Suggestion.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Suggestion` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Suggestion.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Suggestion` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Suggestion.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Suggestion.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Suggestion` objects in a one-to-many relationship (where `Suggestion`.`user` is this object).
  """
  suggestions_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Suggestion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Suggestion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Suggestion_Having
  ): [Suggestion!]! @fdc_generated(from: "Suggestion.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserList` objects in a one-to-many relationship (where `UserList`.`user` is this object).
  """
  userLists_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: UserList_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserList_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserList_Having
  ): [UserList!]! @fdc_generated(from: "UserList.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
extend type UserList {
  """
  ✨ List `ListBusiness` objects in a one-to-many relationship (where `ListBusiness`.`userList` is this object).
  """
  listBusinesses_on_userList(
    """
    Filter condition to narrow down the query results.
    """
    where: ListBusiness_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ListBusiness_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ListBusiness_Having
  ): [ListBusiness!]! @fdc_generated(from: "ListBusiness.userList", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserList", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserList` table.
  """
  _count: Int! @fdc_generated(from: "UserList.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `public` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  public_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.public", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserList` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserList.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `UserList` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "UserList.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `UserList` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "UserList.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `UserList` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "UserList.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `UserList` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "UserList.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserList.id", purpose: ENTITY_ID)
}
