type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Business @table {
  name: String!
  industry: String!
  overallEsgScore: Float!
  createdAt: Timestamp!
  description: String
  website: String
  environmentalScore: Float
  socialScore: Float
  governanceScore: Float
}

type EsgDetail @table {
  business: Business
  category: String!
  description: String!
  createdAt: Timestamp!
  sourceUrl: String
}

type UserList @table {
  user: User
  name: String!
  public: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type ListBusiness @table {
  userList: UserList
  business: Business
  position: Int!
  note: String
}

type Suggestion @table {
  user: User
  type: String!
  status: String!
  createdAt: Timestamp!
  businessName: String
  details: String
  targetBusinessId: UUID
}